import { test, expect } from '@playwright/test';
import { loginForTest } from './auth-helper';

const headers = { Origin: 'http://127.0.0.1:3100' };
test('account edits, current password verification, operator name, and all-device password logout', async ({ page, request }) => {
  await page.goto('/account');
  await expect(page).toHaveURL('http://127.0.0.1:3100/');
  expect((await request.post('/api/auth/profile', { headers, data: {} })).status()).toBe(401);
  const account = await loginForTest(page.request);
  const username = `${account.username}-new`, password = '5678';
  await request.post('/api/auth/login', { headers, data: account });
  await page.goto('/');
  await page.getByRole('link', { name: '내 계정', exact: true }).click();
  const profile = page.locator('section.form-card').filter({ has: page.getByRole('heading', { name: '계정 정보', exact: true }) });
  const security = page.locator('section.form-card').filter({ has: page.getByRole('heading', { name: '비밀번호 변경', exact: true }) });
  await expect(profile.getByLabel('이름', { exact: true })).toHaveValue(account.display_name);
  await page.screenshot({ path: 'work/account-desktop.png', fullPage: true });
  await profile.getByLabel('ID', { exact: true }).fill(username);
  await profile.getByLabel('이름', { exact: true }).fill('수정 담당자');
  await profile.getByLabel('이메일 (선택)').fill('member@example.com');
  await profile.getByLabel('연락처 (선택)').fill('010-1234-5678');
  await profile.getByLabel('부서 (선택)').fill('재고팀');
  await profile.getByLabel('현재 비밀번호', { exact: true }).fill('wrong-password');
  await profile.getByRole('button', { name: '계정 정보 저장' }).click();
  await expect(profile.getByRole('alert')).toContainText('현재 비밀번호');
  await profile.getByLabel('현재 비밀번호', { exact: true }).fill(account.password);
  await profile.getByRole('button', { name: '계정 정보 저장' }).click();
  await expect(profile.getByRole('status')).toContainText('저장했습니다');
  await expect(page.locator('.account-name')).toHaveText('수정 담당자님');
  await expect(profile.getByLabel('현재 비밀번호', { exact: true })).toHaveValue('');
  await page.reload();
  await expect(profile.getByLabel('부서 (선택)')).toHaveValue('재고팀');
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth)).toBe(false);
  await page.screenshot({ path: 'work/account-mobile.png', fullPage: true });
  await page.goto('/');
  await page.getByRole('link', { name: /등록 모델/ }).click();
  await page.locator('.inventory-table').getByRole('link', { name: '입고', exact: true }).first().click();
  await expect(page.getByLabel('담당자', { exact: true })).toHaveValue('수정 담당자');
  await page.goto('/account');
  const rejectedOrigin = await page.request.post('/api/auth/password', { headers: { Origin: 'https://example.com' }, data: { current_password: account.password, new_password: password, password_confirm: password } });
  expect(rejectedOrigin.status()).toBe(403);
  await security.getByLabel('현재 비밀번호', { exact: true }).fill(account.password);
  await security.getByLabel('새 비밀번호', { exact: true }).fill(password);
  await security.getByLabel('새 비밀번호 확인', { exact: true }).fill('mismatch-password');
  await security.getByRole('button', { name: '비밀번호 변경', exact: true }).click();
  await expect(security.getByRole('alert')).toContainText('일치하지');
  await security.getByLabel('새 비밀번호 확인', { exact: true }).fill(password);
  await security.getByRole('button', { name: '비밀번호 변경', exact: true }).click();
  await expect(page).toHaveURL(/password_changed=1/);
  await expect(page.getByRole('status')).toContainText('모든 기기');
  expect((await request.post('/api/inventory', { headers, data: {} })).status()).toBe(401);
  expect((await request.post('/api/auth/login', { headers, data: { username, password: account.password } })).status()).toBe(401);
  await page.getByLabel('ID', { exact: true }).fill(username);
  await page.getByLabel('PW', { exact: true }).fill(password);
  await page.getByRole('button', { name: '로그인', exact: true }).click();
  await expect(page.getByRole('heading', { name: '재고 현황', exact: true })).toBeVisible();
  expect(await page.evaluate(() => JSON.stringify({ local: { ...localStorage }, session: { ...sessionStorage } }))).not.toContain(password);
});

test('mobile category picker stays compact, bounds expanded trees, and closes after selecting', async ({ page }) => {
  await loginForTest(page.request);
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('/');
  const toggle = page.getByRole('button', { name: /카테고리 선택/ });
  await expect(toggle).toHaveAttribute('aria-expanded', 'false');
  await expect(page.locator('#inventory-categories')).not.toBeVisible();
  expect((await page.locator('.tree-filter-card').boundingBox())!.height).toBeLessThan(95);
  await page.screenshot({ path: 'work/categories-mobile-collapsed.png', fullPage: false });
  await toggle.click();
  await expect(page.locator('#inventory-categories')).toBeVisible();
  await page.locator('#inventory-categories details').evaluateAll(nodes => nodes.forEach(node => (node as HTMLDetailsElement).open = true));
  const bounds = await page.locator('#inventory-categories').evaluate(node => ({ height: node.clientHeight, scroll: node.scrollHeight }));
  expect(bounds.height).toBeLessThanOrEqual(360); expect(bounds.scroll).toBeGreaterThan(bounds.height);
  await page.locator('#inventory-categories .next-tree summary a').first().click();
  await expect(page).toHaveURL(/main=/);
  await expect(toggle).toHaveAttribute('aria-expanded', 'false');
  await expect(page.locator('#inventory-categories')).not.toBeVisible();
  await page.setViewportSize({ width: 320, height: 740 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth)).toBe(false);
  await page.setViewportSize({ width: 1440, height: 1000 });
  await expect(toggle).not.toBeVisible();
  await expect(page.locator('#inventory-categories')).toBeVisible();
});

test('top inventory title reloads the first page and clears navigation/search state', async ({ page }) => {
  await loginForTest(page.request);
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('/add');
  await page.evaluate(() => { (window as unknown as { homeReloadMarker?: string }).homeReloadMarker = 'before'; });
  await page.locator('.topbar .home-refresh').click();
  await expect(page).toHaveURL('http://127.0.0.1:3100/');
  expect(await page.evaluate(() => (window as unknown as { homeReloadMarker?: string }).homeReloadMarker)).toBeUndefined();
  await page.getByRole('textbox', { name: '재고 검색' }).fill('임시 검색');
  await page.locator('.topbar .home-refresh').click();
  await expect(page.getByRole('textbox', { name: '재고 검색' })).toHaveValue('');
  await expect(page.locator('.inventory-table')).toHaveCount(0);
  await expect(page.getByRole('heading', { name: '조회할 재고를 선택하세요.' })).toBeVisible();
  await page.getByRole('link', { name: /등록 모델/ }).click();
  await expect(page.locator('.inventory-table')).toBeVisible();
  await page.locator('.topbar .home-refresh').click();
  await expect(page.locator('.inventory-table')).toHaveCount(0);
  await page.getByRole('textbox', { name: '재고 검색' }).fill('존재하지않는검색항목');
  await expect(page.getByRole('heading', { name: '조건에 해당하는 모델이 없습니다.' })).toBeVisible();
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.goto('/transactions');
  await page.locator('.brand-home').click();
  await expect(page).toHaveURL('http://127.0.0.1:3100/');
});
