import { test, expect } from '@playwright/test';
import { randomUUID } from 'node:crypto';

test('signup, device preferences, persistent login, logout and private inventory access', async ({ page, browser, request }) => {
  const id = `member-${randomUUID().slice(0, 8)}`, password = '1234';
  await page.goto('/');
  await expect(page.getByRole('heading', { name: '로그인', exact: true })).toBeVisible();
  await expect(page.locator('.inventory-table')).toHaveCount(0);
  await page.screenshot({ path: 'work/login-desktop.png', fullPage: true });
  expect((await request.post('/api/inventory', { headers: { Origin: 'http://127.0.0.1:3100' }, data: { action: 'item.add' } })).status()).toBe(401);
  await page.goto('/transactions');
  await expect(page).toHaveURL('http://127.0.0.1:3100/');
  await page.getByRole('link', { name: '회원가입', exact: true }).click();
  await page.getByLabel('이름', { exact: true }).fill('홍길동');
  await page.getByLabel('ID', { exact: true }).fill(id);
  await page.getByLabel('PW', { exact: true }).fill(password);
  await page.getByLabel('PW 확인', { exact: true }).fill(password);
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth)).toBe(false);
  await page.screenshot({ path: 'work/signup-mobile.png', fullPage: true });
  await page.getByRole('button', { name: '회원가입', exact: true }).click();
  await expect(page.getByRole('status')).toContainText('회원가입이 완료');
  await page.getByLabel('ID', { exact: true }).fill(id);
  await page.getByLabel('PW', { exact: true }).fill(password);
  await page.getByLabel('ID 저장', { exact: true }).check();
  await page.getByLabel('PW 저장', { exact: true }).check();
  await page.getByLabel('자동로그인', { exact: true }).check();
  await expect(page.locator('input[name="password"]')).toHaveAttribute('autocomplete', 'current-password');
  // Avoid a native browser password-manager prompt in headless automation.
  await page.evaluate(() => { Object.defineProperty(navigator.credentials, 'store', { value: async () => null, configurable: true }); });
  await page.screenshot({ path: 'work/login-mobile.png', fullPage: true });
  await page.getByRole('button', { name: '로그인', exact: true }).click();
  await expect(page.getByRole('heading', { name: '재고 현황', exact: true })).toBeVisible();
  const cookie = (await page.context().cookies()).find(c => c.name === 'jeago_session')!;
  expect(cookie.httpOnly).toBe(true); expect(cookie.sameSite).toBe('Lax');
  expect(cookie.expires).toBeGreaterThan(Date.now() / 1000 + 399 * 86400);
  const renewed = await page.request.post('/api/auth/renew', { headers: { Origin: 'http://127.0.0.1:3100' } });
  expect(renewed.ok()).toBe(true);
  expect(renewed.headers()['set-cookie']).toContain('Max-Age=34560000');
  expect(await page.evaluate(() => document.cookie)).not.toContain('jeago_session');
  const storage = await page.evaluate(() => JSON.stringify({ ...localStorage }));
  expect(storage).toContain(id); expect(storage).not.toContain(password);
  const reopened = await browser.newContext({ storageState: await page.context().storageState() });
  const resumed = await reopened.newPage();
  await resumed.goto('http://127.0.0.1:3100/');
  await expect(resumed.getByRole('heading', { name: '재고 현황', exact: true })).toBeVisible();
  const otherDevice = await browser.newContext();
  const otherPage = await otherDevice.newPage();
  await otherPage.goto('http://127.0.0.1:3100/');
  await expect(otherPage.getByRole('heading', { name: '로그인', exact: true })).toBeVisible();
  await expect(otherPage.getByLabel('ID', { exact: true })).toHaveValue('');
  await page.getByRole('button', { name: '로그아웃', exact: true }).click();
  await expect(page.getByLabel('ID', { exact: true })).toHaveValue(id);
  await expect(page.getByLabel('자동로그인', { exact: true })).not.toBeChecked();
  await resumed.reload();
  await expect(resumed.getByRole('heading', { name: '로그인', exact: true })).toBeVisible();
  await page.getByLabel('ID 저장', { exact: true }).uncheck();
  await page.reload();
  await expect(page.getByLabel('ID', { exact: true })).toHaveValue('');
  await page.getByLabel('ID', { exact: true }).fill(id);
  await page.getByLabel('PW', { exact: true }).fill(password);
  await page.getByLabel('PW 저장', { exact: true }).uncheck();
  await page.getByRole('button', { name: '로그인', exact: true }).click();
  await expect(page.getByRole('heading', { name: '재고 현황', exact: true })).toBeVisible();
  expect((await page.context().cookies()).find(c => c.name === 'jeago_session')!.expires).toBe(-1);
  const temporaryRenewal = await page.request.post('/api/auth/renew', { headers: { Origin: 'http://127.0.0.1:3100' } });
  expect((await temporaryRenewal.json()).remembered).toBe(false);
  expect(temporaryRenewal.headers()['set-cookie']).toBeUndefined();
  await reopened.close(); await otherDevice.close();
  expect((await request.post('/api/auth/login', { headers: { Origin: 'https://example.com' }, data: { username: id, password } })).status()).toBe(403);
});
