import { test, expect } from '@playwright/test';
import { randomUUID } from 'node:crypto';
import { loginForTest } from './auth-helper';
test('inbound source can be saved, viewed and edited without creating a partner',async({page})=>{
  await loginForTest(page.request);
  const name=`입고메모-${randomUUID().slice(0,8)}`;
  await page.goto('/add');
  await page.getByLabel('모델명',{exact:true}).fill(name);
  await page.getByLabel('품목 카테고리').selectOption({index:1});
  await page.getByRole('button',{name:'모델 등록',exact:true}).click();
  await expect(page).toHaveURL(/item=\d+/);
  const id=new URL(page.url()).searchParams.get('item')!;
  await page.goto(`/inbound/${id}`);
  await page.getByLabel('입고 수량').fill('3');
  await page.getByLabel('입고처',{exact:true}).fill(name);
  await page.setViewportSize({width:390,height:844});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false);
  await page.screenshot({path:'work/inbound-source-mobile.png',fullPage:true});
  await page.getByRole('button',{name:'입고 처리',exact:true}).click();
  await expect(page).toHaveURL(/item=\d+/);
  await page.goto(`/history/${id}`);
  await expect(page.locator('[data-label="입고처"]')).toHaveText(name);
  await page.locator('.history-table').getByRole('link',{name:'수정',exact:true}).click();
  await expect(page.getByLabel('입고처',{exact:true})).toHaveValue(name);
  await page.getByLabel('입고처',{exact:true}).fill(name+' 수정');
  await page.getByRole('button',{name:'수정 저장',exact:true}).click();
  await expect(page).toHaveURL(/\/transactions$/);
  await page.goto(`/transactions?q=${encodeURIComponent(name+' 수정')}`);
  await expect(page.locator('.history-table tbody tr')).toHaveCount(1);
  await expect(page.locator('[data-label="입고처"]')).toHaveText(name+' 수정');
  await page.goto(`/partners?q=${encodeURIComponent(name)}`);
  await expect(page.locator('.next-partner')).toHaveCount(0);
  await page.goto(`/outbound/${id}`);
  await expect(page.getByLabel('입고처',{exact:true})).toHaveCount(0);
  await expect(page.getByRole('combobox',{name:'출고업체',exact:true})).toBeVisible();
});
