import { test, expect } from '@playwright/test';
import { DatabaseSync } from 'node:sqlite';
import { randomUUID } from 'node:crypto';
import { loginForTest } from './auth-helper';
test('legacy data renders, forms work, and desktop/mobile routes are usable', async ({ page, request }) => {
  const account = await loginForTest(page.request);
  await request.post('/api/auth/login', { headers: { Origin: 'http://127.0.0.1:3100' }, data: account });
  const errors: string[] = [];
  page.on('pageerror', e => errors.push(e.message));
  const database = new DatabaseSync('instance/inventory-next.db', { readOnly: true });
  const count = Number(database.prepare('SELECT COUNT(*) AS n FROM item').get()!.n);
  const first = database.prepare('SELECT * FROM item ORDER BY name,id LIMIT 1').get()!;
  database.close();
  expect((await request.get('/health')).status()).toBe(200);
  await page.goto('/?stock=all');
  await expect(page.locator('.inventory-table tbody tr')).toHaveCount(count);
  await expect(page.getByRole('heading', { name: '재고 현황' })).toBeVisible();
  await page.screenshot({ path: 'work/nextjs-desktop.png', fullPage: false });
  await page.goto(`/?category=${first.category}`);
  const treeItem = page.locator(`.category-tree a[href="/?category=${first.category}&item=${first.id}#item-${first.id}"]`);
  await expect(treeItem).toBeVisible();
  expect((await treeItem.locator('span').boundingBox())!.width).toBeGreaterThan(50);
  await page.goto('/');
  await page.getByRole('textbox', { name: '재고 검색' }).fill('존재하지않는모델-E2E');
  await expect(page.getByText('조건에 해당하는 모델이 없습니다.')).toBeVisible();
  await page.getByRole('textbox', { name: '재고 검색' }).fill(String(first.name));
  await expect(page.locator(`#item-${first.id}`)).toBeVisible();

  await page.goto('/add');
  await expect(page.getByLabel('담당자', { exact: true })).toHaveValue(account.display_name);
  await expect(page.getByLabel('담당자', { exact: true })).toHaveAttribute('readonly', '');
  await page.getByRole('textbox', { name: '모델명', exact: true }).fill('E2E-재고모델');
  await page.getByLabel('품목 카테고리').selectOption(String(first.category));
  await page.getByRole('button', { name: '모델 등록', exact: true }).click();
  await expect(page).toHaveURL(/item=\d+/);
  const id = new URL(page.url()).searchParams.get('item');
  const row = page.locator(`#item-${id}`);
  await expect(row.locator('td[data-label="담당자"]')).toHaveText(account.display_name);
  await expect(row).toContainText('E2E-재고모델');
  await row.getByRole('link', { name: '입고', exact: true }).click();
  await expect(page.getByLabel('담당자', { exact: true })).toHaveValue(account.display_name);
  await expect(page.getByLabel('담당자', { exact: true })).toHaveAttribute('readonly', '');
  await page.getByLabel('입고 수량').fill('10');
  await page.getByRole('button', { name: '입고 처리' }).click();
  await expect(page).toHaveURL(/item=\d+/);
  await expect(page.locator(`#item-${id} .qty-value`)).toHaveText('10');
  await page.locator(`#item-${id}`).getByRole('link', { name: '출고', exact: true }).click();
  await expect(page.getByLabel('담당자', { exact: true })).toHaveValue(account.display_name);
  await page.getByLabel('출고 수량').fill('3');
  await page.getByLabel('출고업체').fill('E2E-거래처');
  await page.getByRole('button', { name: '출고 처리' }).click();
  await expect(page).toHaveURL(/item=\d+/);
  await expect(page.locator(`#item-${id} .qty-value`)).toHaveText('7');
  await page.locator(`#item-${id}`).getByRole('spinbutton', { name: 'E2E-재고모델 부족 기준', exact: true }).fill('8');
  await page.locator(`#item-${id}`).getByRole('button', { name: '저장', exact: true }).click();
  await expect(page.locator(`#item-${id} .stock-badge`)).toHaveText('부족');
  await page.locator(`#item-${id}`).getByRole('button', { name: / · / }).click();
  await expect(page.getByRole('dialog')).toBeVisible();
  await page.getByRole('dialog').getByRole('button', { name: '저장', exact: true }).click();
  await expect(page.getByRole('dialog')).not.toBeVisible();
  await page.goto(`/history/${id}`);
  await expect(page.locator('.history-table tbody tr')).toHaveCount(2);
  for (const cell of await page.locator('.history-table tbody td[data-label="담당자"]').all()) await expect(cell).toHaveText(account.display_name);
  await expect(page.locator('.history-table tbody tr').first().locator('td').first()).toHaveText(/\d{4}-\d{2}-\d{2} \d{2}:\d{2}/);
  await expect(page.locator('.history-table tbody tr').first()).toContainText('E2E-거래처');
  await page.goto(`/edit/${id}`);
  await expect(page.getByLabel('담당자', { exact: true })).toHaveValue(account.display_name);
  await page.getByLabel('모델명', { exact: true }).fill('E2E-수정모델');
  await page.getByRole('button', { name: '변경 저장' }).click();
  await expect(page).toHaveURL(/item=\d+/);
  await expect(page.locator(`#item-${id}`)).toContainText('E2E-수정모델');
  await page.goto('/transactions?q=E2E&type=출고');
  await expect(page.locator('.history-table tbody tr')).toHaveCount(1);

  await page.goto('/partners');
  const addPartner = page.locator('.partner-form-card');
  await addPartner.getByLabel('거래처명').fill('E2E-파트너');
  await addPartner.getByLabel('담당자').fill('테스터');
  await addPartner.getByRole('button', { name: '+ 거래처 추가' }).click();
  const partner = page.locator('.next-partner').filter({ has: page.locator('input[value="E2E-파트너"]') });
  await expect(partner).toBeVisible();
  await partner.getByLabel('연락처').fill('010-0000-0000');
  await partner.getByRole('button', { name: '수정 저장' }).click();
  await expect(partner.getByLabel('연락처')).toHaveValue('010-0000-0000');
  await expect(partner.getByRole('button', { name: '수정 저장' })).toBeEnabled();
  await page.reload();
  await expect(partner.getByLabel('연락처')).toHaveValue('010-0000-0000');

  await page.goto('/categories');
  await expect(page.getByRole('heading', { name: '카테고리 구조' })).toBeVisible();
  const rootForm = page.locator('.category-create-stack .form-card').nth(0);
  await rootForm.getByLabel('대분류 이름').fill('E2E-대분류');
  await rootForm.getByRole('button', { name: '추가', exact: true }).click();
  const main = page.locator('.admin-node.level-0').filter({ has: page.locator('summary>strong', { hasText: 'E2E-대분류' }) });
  await expect(main).toBeVisible();
  const deviceForm = page.locator('.category-create-stack .form-card').nth(1);
  await deviceForm.getByRole('combobox').selectOption({ label: 'E2E-대분류' });
  await deviceForm.getByLabel('장비 모델 이름').fill('E2E-장비');
  await deviceForm.getByRole('button', { name: '추가', exact: true }).click();
  await expect(main.locator('.level-1>summary')).toContainText('E2E-장비');
  const leafForm = page.locator('.category-create-stack .form-card').nth(2);
  await leafForm.getByRole('combobox').selectOption({ label: 'E2E-대분류 · E2E-장비' });
  await leafForm.getByLabel('품목 카테고리 이름').fill('E2E-품목');
  await leafForm.getByRole('button', { name: '추가', exact: true }).click();
  await main.locator('.level-1>summary').click();
  await expect(main.locator('.level-2>summary')).toContainText('E2E-품목');
  await page.screenshot({ path: 'work/nextjs-categories.png', fullPage: false });

  await page.setViewportSize({ width: 390, height: 844 });
  for (const route of ['/', '/add', '/partners', '/categories', '/transactions', `/history/${id}`, `/outbound/${id}`]) {
    await page.goto(route);
    await expect(page.locator('.mobile-nav')).toBeVisible();
    const overflow = await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth);
    expect(overflow, `no horizontal page overflow at ${route}`).toBe(false);
  }
  await page.goto(`/?category=${first.category}&item=${id}`);
  await page.getByRole('textbox', { name: '재고 검색' }).fill('E2E-수정모델');
  await page.screenshot({ path: 'work/nextjs-mobile.png', fullPage: true });
  page.on('dialog', dialog => dialog.accept());
  await page.locator(`#item-${id}`).getByRole('button', { name: '삭제', exact: true }).click();
  await expect(page.locator(`#item-${id}`)).toHaveCount(0);
  expect((await request.get('/unknown-page')).status()).toBe(404);
  const crossSite = await request.post('/api/inventory', { headers: { Origin: 'https://example.com' }, data: { action: 'item.delete', id: first.id } });
  expect(crossSite.status()).toBe(403);
  const invalid = await request.post('/api/inventory', { headers: { Origin: 'http://127.0.0.1:3100' }, data: { action: 'stock.in', id: first.id, quantity: -1, manager: '김채희', request_id: randomUUID(), expected_version: 0 } });
  expect(invalid.status()).toBe(400);
  expect(errors).toEqual([]);
});
