import { test, expect } from '@playwright/test';
import { loginForTest } from './auth-helper';
import { readdirSync, statSync } from 'node:fs';
import { join } from 'node:path';
import { DatabaseSync } from 'node:sqlite';
import { randomUUID } from 'node:crypto';
test('own leave defaults to login and saves or edits entries with one button', async ({ page, request }) => {
  expect((await request.get('/api/leave')).status()).toBe(401);
  const account = await loginForTest(page.request);
  await page.setViewportSize({width:390,height:844}); await page.goto('/');
  await page.getByRole('link',{name:'연차계산',exact:true}).click();
  await expect(page).toHaveURL(/\/leave$/);
  await expect(page.getByRole('navigation',{name:'모바일 메뉴'}).getByRole('link',{name:/모델 등록/})).toBeVisible();
  await expect(page.getByLabel('직원 선택')).toHaveCount(0);
  await expect(page.getByLabel('로그인 계정')).toHaveValue(new RegExp(account.username));
  await page.getByLabel('입사일',{exact:true}).fill('2024-06-03');
  await page.getByLabel('계산 기준일').fill('2026-08-25');
  await page.getByLabel('특별연차').fill('1');
  await page.getByLabel('사용 시작일').fill('2026-08-24');
  await page.getByLabel('사용 종료일').fill('2026-08-24');
  await page.getByRole('button',{name:'반차 0.5일'}).click();
  await expect(page.getByRole('button',{name:'사용 내역 추가',exact:true})).toHaveCount(0);
  await page.getByRole('button',{name:'연차 내역 저장'}).click();
  await expect(page.getByText('연차 내역을 저장했습니다.', { exact: true })).toBeVisible();
  await expect(page.locator('.leave-totals')).toContainText('32.5일');
  await page.reload();
  await expect(page.getByLabel('성명',{exact:true})).toHaveValue('화면 테스트');
  await expect(page.locator('.leave-history')).toContainText('0.5일');
  await page.getByRole('button',{name:'연차 내역 저장'}).click();
  await expect(page.getByText('연차 내역을 저장했습니다.', { exact: true })).toBeVisible();
  await expect(page.locator('.leave-history-row')).toHaveCount(1);
  await expect(page.locator('.leave-history-row').getByRole('button',{name:'수정'})).toHaveCount(0);
  await expect(page.getByRole('button',{name:'삭제',exact:true})).toHaveCount(0);
  expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false);
  await page.screenshot({path:'work/leave-mobile.png',fullPage:true});
  await page.setViewportSize({width:1440,height:1000});
  await page.screenshot({path:'work/leave-desktop.png',fullPage:true});
  await loginForTest(request);
  const own=(await (await page.request.get('/api/leave')).json()).employees[0];
  const otherId=randomUUID();
  expect((await request.post('/api/leave',{headers:{Origin:'http://127.0.0.1:3100'},data:{employee:{...own,id:otherId,version:0},request_id:randomUUID()}})).ok()).toBe(true);
  const file=readdirSync('work').filter(name=>/^browser-[a-f0-9-]+\.db$/.test(name)).map(name=>join('work',name)).sort((a,b)=>statSync(b).birthtimeMs-statSync(a).birthtimeMs)[0];
  const fixture=new DatabaseSync(file);
  try { const user=fixture.prepare('SELECT id FROM app_user WHERE username=?').get(account.username); if(!user)throw new Error('Isolated fixture mismatch');fixture.prepare('INSERT INTO leave_admin(user_id) VALUES (?)').run(String(user.id)); } finally { fixture.close(); }
  await page.reload();
  await expect(page.getByLabel('직원 선택')).toHaveValue(own.id);
  await page.getByLabel('직원 선택').selectOption(otherId);
  await page.locator('.leave-history-row').getByRole('button',{name:'수정'}).click();
  await page.getByLabel('사용 일수').fill('1');
  await page.getByRole('button',{name:'연차 내역 저장'}).click();
  await expect(page.getByText('연차 내역을 저장했습니다.',{exact:true})).toBeVisible();
  await expect(page.locator('.leave-history-row')).toContainText('1일');
  expect((await page.request.get('/api/admin/users')).status()).toBe(403);
  await expect(page.getByRole('button',{name:'삭제',exact:true})).toHaveCount(0);
});
