import { test, expect } from '@playwright/test';
import { loginForTest } from './auth-helper';
test('leave replaces header shortcut, saves half-day dates and is shared on mobile', async ({ page, request }) => {
  expect((await request.get('/api/leave')).status()).toBe(401);
  await loginForTest(page.request);
  await page.setViewportSize({width:390,height:844}); await page.goto('/');
  await page.getByRole('link',{name:'연차계산',exact:true}).click();
  await expect(page).toHaveURL(/\/leave$/);
  await expect(page.getByRole('navigation',{name:'모바일 메뉴'}).getByRole('link',{name:/모델 등록/})).toBeVisible();
  await page.getByLabel('직원 선택').selectOption('new');
  await page.getByLabel('성명',{exact:true}).fill('연차테스트');
  await page.getByLabel('입사일',{exact:true}).fill('2024-06-03');
  await page.getByLabel('계산 기준일').fill('2026-08-25');
  await page.getByLabel('특별연차').fill('1');
  await page.getByLabel('사용 시작일').fill('2026-08-24');
  await page.getByLabel('사용 종료일').fill('2026-08-24');
  await page.getByRole('button',{name:'반차 0.5일'}).click();
  await page.getByRole('button',{name:'사용 내역 추가',exact:true}).click();
  await expect(page.locator('.leave-totals')).toContainText('32.5일');
  await page.getByRole('button',{name:'연차 내역 저장'}).click();
  await expect(page.getByText('연차 내역을 저장했습니다.', { exact: true })).toBeVisible();
  await page.reload();
  await expect(page.getByLabel('성명',{exact:true})).toHaveValue('연차테스트');
  await expect(page.locator('.leave-history')).toContainText('0.5일');
  expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false);
  await page.screenshot({path:'work/leave-mobile.png',fullPage:true});
  await page.setViewportSize({width:1440,height:1000});
  await page.screenshot({path:'work/leave-desktop.png',fullPage:true});
});
