import { test, expect } from '@playwright/test';
import { randomUUID } from 'node:crypto';
import { DatabaseSync } from 'node:sqlite';
import { loginForTest } from './auth-helper';

test('outbound autocomplete, automatic partners, and confirmed individual/all permanent deletion', async ({ page, request }) => {
  await loginForTest(page.request);
  const headers = { Origin: 'http://127.0.0.1:3100' };
  expect((await request.post('/api/inventory', { headers, data: { action: 'trash.empty', request_id: randomUUID() } })).status()).toBe(401);
  const db = new DatabaseSync('instance/inventory-next.db', { readOnly: true });
  const category = String(db.prepare('SELECT category FROM item LIMIT 1').get()!.category); db.close();
  async function mutate(fields: Record<string, unknown>) {
    const response = await page.request.post('/api/inventory', { headers, data: { ...fields, request_id: randomUUID() } });
    expect(response.ok(), await response.text()).toBeTruthy(); return response.json();
  }
  const added = await mutate({ action: 'item.add', name: 'E2E-영구삭제대상', category, manager: '김채희' });
  const id = Number(new URL(added.redirect, 'http://localhost').searchParams.get('item'));
  await mutate({ action: 'stock.in', id, quantity: 6, expected_version: 0 });
  await mutate({ action: 'stock.out', id, quantity: 1, customer_name: '베스트시스템', expected_version: 1 });
  await mutate({ action: 'stock.out', id, quantity: 1, customer_name: '베스트아이티', expected_version: 2 });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto(`/outbound/${id}`);
  await page.getByLabel('출고 수량').fill('1');
  const customer = page.getByRole('combobox', { name: '출고업체' });
  await customer.fill('베스');
  await expect(page.getByRole('option', { name: '베스트시스템', exact: true })).toBeVisible();
  await expect(page.getByRole('option', { name: '베스트아이티', exact: true })).toBeVisible();
  await customer.fill('베스트시');
  await expect(page.getByRole('option')).toHaveCount(1);
  await page.screenshot({ path: 'work/partner-suggestions-mobile.png', fullPage: true });
  await customer.press('ArrowDown'); await customer.press('Enter');
  await expect(customer).toHaveValue('베스트시스템');
  await expect(customer).toHaveAttribute('aria-expanded', 'false');
  await page.getByRole('button', { name: '출고 처리', exact: true }).click();
  await expect(page).toHaveURL(/item=/);
  await page.goto('/partners?q=베스트시스템');
  await expect(page.locator('.next-partner')).toHaveCount(1);
  await page.goto(`/outbound/${id}`);
  await customer.fill('베스');
  await page.getByRole('option', { name: '베스트아이티', exact: true }).click();
  await expect(customer).toHaveValue('베스트아이티');
  await page.goto(`/history/${id}`);
  await expect(page.locator('.history-table tbody tr')).toHaveCount(4);
  await mutate({ action: 'item.delete', id, expected_version: 4 });
  await page.goto('/trash');
  const row = page.locator('.trash-entry').filter({ hasText: 'E2E-영구삭제대상' });
  await expect(row).toBeVisible();
  page.once('dialog', dialog => dialog.dismiss());
  await row.getByRole('button', { name: '영구 삭제', exact: true }).click();
  await expect(row).toBeVisible();
  await page.screenshot({ path: 'work/trash-mobile.png', fullPage: true });
  page.once('dialog', dialog => { expect(dialog.message()).toContain('복구할 수 없습니다'); return dialog.accept(); });
  await row.getByRole('button', { name: '영구 삭제', exact: true }).click();
  await expect(row).toHaveCount(0);
  expect((await page.request.get(`/history/${id}`)).status()).toBe(404);
  await mutate({ action: 'partner.add', name: 'E2E-비우기전용' });
  await page.goto('/partners?q=E2E-비우기전용');
  page.once('dialog', dialog => dialog.accept());
  await page.locator('.next-partner').getByRole('button', { name: '삭제', exact: true }).click();
  await expect(page.locator('.next-partner')).toHaveCount(0);
  await page.goto('/trash');
  page.once('dialog', dialog => dialog.dismiss());
  await page.getByRole('button', { name: '전체 비우기' }).click();
  await expect(page.locator('.trash-entry').filter({ hasText: 'E2E-비우기전용' })).toBeVisible();
  page.once('dialog', dialog => { expect(dialog.message()).toContain('복구할 수 없습니다'); return dialog.accept(); });
  await page.getByRole('button', { name: '전체 비우기' }).click();
  await expect(page.getByRole('heading', { name: '휴지통이 비어 있습니다.' })).toBeVisible();
  await page.goto('/partners?q=베스트');
  await expect(page.locator('.next-partner')).toHaveCount(2);
  expect(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth)).toBe(false);
});
