import { after, test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdirSync, mkdtempSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
import { getDb } from '../src/lib/db';
import { register, createSession, authenticate, sessionUser, updateAccount, revokeSession, AuthError } from '../src/lib/auth';
import { isAdministrator, listMembers, editMember } from '../src/lib/admin';
mkdirSync('work', { recursive: true });
process.env.JEAGO_TEST_MODE = '1';
process.env.JEAGO_TEST_DATABASE_URL = pathToFileURL(join(mkdtempSync(join(resolve('work'), 'admin-test-')), 'test.db')).href;
after(async () => (await getDb()).close());
test('only the explicitly assigned immutable account can manage members', async () => {
  const password = '1234';
  const admin = await register({ username: 'jcsh44', display_name: '관리자', password, password_confirm: password });
  const member = await register({ username: 'normal.member', display_name: '회원', password, password_confirm: password });
  const adminToken = await createSession(admin.id, true), memberToken = await createSession(member.id, true), secondDevice = await createSession(member.id, true);
  assert.equal(await isAdministrator(admin.id), false);
  await assert.rejects(listMembers(adminToken), error => error instanceof AuthError && error.status === 403);
  await (await getDb()).execute({ sql: 'INSERT INTO app_admin(singleton,user_id) VALUES (1,?)', args: [admin.id] });
  assert.equal(await isAdministrator(admin.id), true);
  await assert.rejects(listMembers(undefined), error => error instanceof AuthError && error.status === 401);
  await assert.rejects(listMembers(memberToken), error => error instanceof AuthError && error.status === 403);
  const fields = { target_id: member.id, expected_version: 0, admin_password: password, username: 'edited.member', display_name: '수정 회원', email: 'member@example.com', phone: '010-1234', department: '물류팀', is_admin: true };
  await assert.rejects(editMember(memberToken, 'admin-profile', fields), error => error instanceof AuthError && error.status === 403);
  await assert.rejects(editMember(adminToken, 'admin-profile', { ...fields, admin_password: '0000' }), /비밀번호/);
  await assert.rejects(editMember(adminToken, 'admin-profile', { ...fields, username: admin.username }), error => error instanceof AuthError && error.status === 409);
  await editMember(adminToken, 'admin-profile', fields);
  assert.equal(await isAdministrator(member.id), false);
  assert.equal((await sessionUser(memberToken))!.display_name, '수정 회원');
  await assert.rejects(editMember(adminToken, 'admin-profile', fields), error => error instanceof AuthError && error.status === 409);
  const members = await listMembers(adminToken);
  assert(!JSON.stringify(members).includes('password_hash'));
  assert.equal(members.find(m => m.id === member.id)!.department, '물류팀');
  await editMember(adminToken, 'admin-password', { target_id: member.id, expected_version: 1, admin_password: password, new_password: '5678', password_confirm: '5678' });
  assert.equal(await sessionUser(memberToken), null); assert.equal(await sessionUser(secondDevice), null);
  assert.equal((await authenticate({ username: 'edited.member', password: '5678' })).id, member.id);
  assert(await sessionUser(adminToken));
  await assert.rejects(editMember(adminToken, 'admin-profile', { ...fields, target_id: admin.id }), /내 계정/);
  await updateAccount(adminToken, 'profile', { username: 'renamed.admin', display_name: '관리자', current_password: password });
  const pretender = await register({ username: 'jcsh44', display_name: '동일 ID 새 계정', password, password_confirm: password });
  assert.equal(await isAdministrator(admin.id), true);
  assert.equal(await isAdministrator(pretender.id), false);
  assert.equal((await (await getDb()).execute('SELECT COUNT(*) AS n FROM admin_audit')).rows[0].n, 2);
  const transfer = { target_id: member.id, expected_version: 2, admin_password: password, confirm_username: 'edited.member' };
  const newAdminToken = await createSession(member.id, true);
  await assert.rejects(editMember(newAdminToken, 'admin-transfer', transfer), error => error instanceof AuthError && error.status === 403);
  await assert.rejects(editMember(adminToken, 'admin-transfer', { ...transfer, admin_password: '0000' }), /비밀번호/);
  await assert.rejects(editMember(adminToken, 'admin-transfer', { ...transfer, confirm_username: 'wrong' }), /회원 ID/);
  await assert.rejects(editMember(adminToken, 'admin-transfer', { ...transfer, expected_version: 0 }), error => error instanceof AuthError && error.status === 409);
  const results = await Promise.allSettled([editMember(adminToken, 'admin-transfer', transfer), editMember(adminToken, 'admin-transfer', transfer)]);
  assert.equal(results.filter(r => r.status === 'fulfilled').length, 1);
  assert.equal(await isAdministrator(admin.id), false);
  assert.equal(await isAdministrator(member.id), true);
  assert.equal((await (await getDb()).execute('SELECT COUNT(*) AS n FROM app_admin')).rows[0].n, 1);
  assert.equal((await (await getDb()).execute("SELECT COUNT(*) AS n FROM admin_audit WHERE action='admin-transfer'")).rows[0].n, 1);
  await assert.rejects(listMembers(adminToken), error => error instanceof AuthError && error.status === 403);
  await assert.rejects(editMember(adminToken, 'admin-profile', fields), error => error instanceof AuthError && error.status === 403);
  assert((await listMembers(newAdminToken)).length > 0);
  const victimToken=await createSession(pretender.id,true);
  const db=await getDb();
  await db.execute({sql:'INSERT INTO leave_admin(user_id) VALUES (?)',args:[pretender.id]});
  await db.execute({sql:'INSERT INTO leave_employee(id,name,position,hired,entries,user_id) VALUES (?,?,?,?,?,?)',args:['retained-leave','기존 이름','사원','2025-01-01','[]',pretender.id]});
  const deletion={target_id:pretender.id,expected_version:0,admin_password:'5678',confirm_username:'jcsh44'};
  await assert.rejects(editMember(victimToken,'admin-delete',deletion), /관리자만/);
  await assert.rejects(editMember(newAdminToken,'admin-delete',{...deletion,admin_password:'0000'}), /비밀번호/);
  await assert.rejects(editMember(newAdminToken,'admin-delete',{...deletion,confirm_username:'wrong'}), /회원 ID/);
  await assert.rejects(editMember(newAdminToken,'admin-delete',{...deletion,target_id:member.id}), /내 계정/);
  await editMember(newAdminToken,'admin-delete',deletion);
  assert.equal(await sessionUser(victimToken),null);
  await assert.rejects(authenticate({username:'jcsh44',password}));
  assert.equal((await db.execute('SELECT user_id FROM leave_employee WHERE id=\'retained-leave\'')).rows[0].user_id,null);
  assert.equal((await db.execute({sql:'SELECT * FROM leave_admin WHERE user_id=?',args:[pretender.id]})).rows.length,0);
  const rejoined=await register({username:'jcsh44',display_name:'새 회원',password,password_confirm:password});
  assert.notEqual(rejoined.id,pretender.id);
  assert.equal(await isAdministrator(rejoined.id),false);
  await revokeSession(adminToken);
  await assert.rejects(editMember(adminToken, 'admin-profile', fields), error => error instanceof AuthError && error.status === 401);
});
