import { after, test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdirSync, mkdtempSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
import { getDb } from '../src/lib/db';
import { register, createSession, authenticate, sessionUser, updateAccount, revokeSession, AuthError } from '../src/lib/auth';
import { isAdministrator, listMembers, editMember } from '../src/lib/admin';
mkdirSync('work', { recursive: true });
process.env.JEAGO_TEST_MODE = '1';
process.env.JEAGO_TEST_DATABASE_URL = pathToFileURL(join(mkdtempSync(join(resolve('work'), 'admin-test-')), 'test.db')).href;
after(async () => (await getDb()).close());
test('only the explicitly assigned immutable account can manage members', async () => {
  const password = '1234';
  const admin = await register({ username: 'jcsh44', display_name: '관리자', password, password_confirm: password });
  const member = await register({ username: 'normal.member', display_name: '회원', password, password_confirm: password });
  const adminToken = await createSession(admin.id, true), memberToken = await createSession(member.id, true), secondDevice = await createSession(member.id, true);
  assert.equal(await isAdministrator(admin.id), false);
  await assert.rejects(listMembers(adminToken), error => error instanceof AuthError && error.status === 403);
  await (await getDb()).execute({ sql: 'INSERT INTO app_admin(singleton,user_id) VALUES (1,?)', args: [admin.id] });
  assert.equal(await isAdministrator(admin.id), true);
  await assert.rejects(listMembers(undefined), error => error instanceof AuthError && error.status === 401);
  await assert.rejects(listMembers(memberToken), error => error instanceof AuthError && error.status === 403);
  const fields = { target_id: member.id, expected_version: 0, admin_password: password, username: 'edited.member', display_name: '수정 회원', email: 'member@example.com', phone: '010-1234', department: '물류팀', is_admin: true };
  await assert.rejects(editMember(memberToken, 'admin-profile', fields), error => error instanceof AuthError && error.status === 403);
  await assert.rejects(editMember(adminToken, 'admin-profile', { ...fields, admin_password: '0000' }), /비밀번호/);
  await assert.rejects(editMember(adminToken, 'admin-profile', { ...fields, username: admin.username }), error => error instanceof AuthError && error.status === 409);
  await editMember(adminToken, 'admin-profile', fields);
  assert.equal(await isAdministrator(member.id), false);
  assert.equal((await sessionUser(memberToken))!.display_name, '수정 회원');
  await assert.rejects(editMember(adminToken, 'admin-profile', fields), error => error instanceof AuthError && error.status === 409);
  const members = await listMembers(adminToken);
  assert(!JSON.stringify(members).includes('password_hash'));
  assert.equal(members.find(m => m.id === member.id)!.department, '물류팀');
  await editMember(adminToken, 'admin-password', { target_id: member.id, expected_version: 1, admin_password: password, new_password: '5678', password_confirm: '5678' });
  assert.equal(await sessionUser(memberToken), null); assert.equal(await sessionUser(secondDevice), null);
  assert.equal((await authenticate({ username: 'edited.member', password: '5678' })).id, member.id);
  assert(await sessionUser(adminToken));
  await assert.rejects(editMember(adminToken, 'admin-profile', { ...fields, target_id: admin.id }), /내 계정/);
  await updateAccount(adminToken, 'profile', { username: 'renamed.admin', display_name: '관리자', current_password: password });
  const pretender = await register({ username: 'jcsh44', display_name: '동일 ID 새 계정', password, password_confirm: password });
  assert.equal(await isAdministrator(admin.id), true);
  assert.equal(await isAdministrator(pretender.id), false);
  assert.equal((await (await getDb()).execute('SELECT COUNT(*) AS n FROM admin_audit')).rows[0].n, 2);
  await revokeSession(adminToken);
  await assert.rejects(editMember(adminToken, 'admin-profile', fields), error => error instanceof AuthError && error.status === 401);
});
