import { after, test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdirSync, mkdtempSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
import { randomUUID } from 'node:crypto';
import { getDb } from '../src/lib/db';
import { loadInventory, mutate } from '../src/lib/inventory';
import { koreaDateTimeInput } from '../src/lib/korea-time';
mkdirSync('work',{recursive:true});
process.env.JEAGO_TEST_MODE='1';
process.env.JEAGO_TEST_DATABASE_URL=pathToFileURL(join(mkdtempSync(join(resolve('work'),'inbound-note-')),'test.db')).href;
after(async()=>(await getDb()).close());
test('inbound source is an optional note, never a partner or outbound suggestion',async()=>{
  const actor={id:'employee',display_name:'직원'};
  const root=(await loadInventory()).categories[0];
  await mutate({action:'category.add',level:1,parent_id:root.id,name:'장비'});
  const device=(await loadInventory()).categories.find(c=>c.display_name==='장비')!;
  await mutate({action:'category.add',level:2,parent_id:device.id,name:'품목'});
  const category=(await loadInventory()).categories.find(c=>c.display_name==='품목')!.name;
  await mutate({action:'item.add',name:'모델',category},actor);
  const id=(await loadInventory()).items[0].id;
  const request={action:'stock.in',id,quantity:3,inbound_source:'  입고처 메모  ',customer_name:'입고에 잘못 보낸 업체',request_id:randomUUID()};
  await mutate(request,actor);await mutate(request,actor);
  let data=await loadInventory();
  assert.equal(data.items[0].quantity,3);
  assert.equal(data.transactions.length,1);
  assert.equal(data.transactions[0].inbound_source,'입고처 메모');
  assert.equal(data.transactions[0].customer_name,null);
  assert.deepEqual(data.partners,[]);assert.deepEqual(data.customerNames,[]);
  const row=data.transactions[0],item=data.items[0];
  const edit={action:'transaction.edit',id:row.id,original_item_id:id,item_id:id,expected_version:row.version,expected_item_version:item.version,expected_target_version:item.version,quantity:row.quantity,transaction_type:'입고',manager:row.manager,date:koreaDateTimeInput(row.date),inbound_source:'수정된 입고 메모',request_id:randomUUID()};
  await mutate(edit,actor);
  data=await loadInventory();
  assert.equal(data.transactions[0].inbound_source,'수정된 입고 메모');
  assert.equal(data.items[0].quantity,3);
  assert.deepEqual(data.partners,[]);assert.deepEqual(data.customerNames,[]);
  const {inbound_source,...oldClientEdit}=edit;
  await mutate({...oldClientEdit,expected_version:1,request_id:randomUUID()},actor);
  assert.equal((await loadInventory()).transactions[0].inbound_source,'수정된 입고 메모');
  await assert.rejects(mutate({action:'stock.in',id,quantity:1,inbound_source:'x'.repeat(121)},actor));
  await mutate({action:'stock.in',id,quantity:1},actor);
  data=await loadInventory();
  assert.equal(data.transactions.at(-1)!.inbound_source,null);
  assert.equal(data.items[0].quantity,4);
  assert.deepEqual(data.partners,[]);
  await mutate({action:'stock.out',id,quantity:1,customer_name:'기존 출고 거래처',inbound_source:'무시할 메모'},actor);
  data=await loadInventory();
  assert.deepEqual(data.partners.map(p=>p.name),['기존 출고 거래처']);
  assert.deepEqual(data.customerNames,['기존 출고 거래처']);
  assert.equal(data.transactions.at(-1)!.inbound_source,null);
});
