import { after, test } from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { mkdirSync, mkdtempSync } from 'node:fs';
import { resolve, join } from 'node:path';
import { pathToFileURL } from 'node:url';
import { calculateLeave, weekdays } from '../src/lib/leave-calculator';
import { saveLeave, leaveEmployees } from '../src/lib/leave-store';
import { register, createSession } from '../src/lib/auth';
import { getDb } from '../src/lib/db';
mkdirSync('work', { recursive: true });
process.env.JEAGO_TEST_MODE = '1';
process.env.JEAGO_TEST_DATABASE_URL = pathToFileURL(join(mkdtempSync(join(resolve('work'),'leave-test-')),'test.db')).href;
after(async () => (await getDb()).close());
test('leave calculation matches supplied workbook cached examples and date boundaries', () => {
  const examples = [['2024-06-03',1,34,33,-1],['2024-02-21',1,35,39,4],['2020-12-14',0,87,90,3],['2025-01-21',0,24.5,23,-1.5],['2025-01-02',0,22,23,1]] as const;
  for (const [hired,special,used,earned,remaining] of examples) { const result=calculateLeave(hired,'2026-08-25',special,used); assert.equal(result.earned,earned); assert.equal(result.remaining,remaining); }
  assert.equal(calculateLeave('2025-01-31','2025-02-28',0,0).months,0);
  assert.equal(calculateLeave('2024-02-29','2025-02-28',0,0).earned,11);
  assert.equal(calculateLeave('2024-02-29','2025-03-01',0,0).earned,15);
  assert.equal(calculateLeave('2020-01-01','2023-01-01',0,0).earned,46);
  assert.throws(() => calculateLeave('2025-02-30','2026-01-01',0,0));
  assert.throws(() => calculateLeave('2025-02-01','2025-01-01',0,0));
  assert.equal(weekdays('2026-09-18','2026-09-21'),2);
});
test('leave ownership prevents cross-account reads, edits and impersonation', async () => {
  const a=await register({username:'leave.a',display_name:'A',password:'1234',password_confirm:'1234'});
  const b=await register({username:'leave.b',display_name:'B',password:'1234',password_confirm:'1234'});
  const token=await createSession(a.id,true), other=await createSession(b.id,true);
  const employee={id:randomUUID(),name:'테스트',position:'사원',hired:'2025-01-01',special:1,version:0,entries:[{id:randomUUID(),start:'2026-01-02',end:'2026-01-02',days:0.5,note:''}]};
  const request={employee,request_id:randomUUID()};
  await assert.rejects(saveLeave(undefined,request)); await assert.rejects(leaveEmployees(undefined));
  await saveLeave(token,request); await saveLeave(token,request);
  assert.equal((await leaveEmployees(token))[0].version,1);
  assert.deepEqual(await leaveEmployees(other),[]);
  await assert.rejects(saveLeave(other,{...request,request_id:randomUUID()}),/본인/);
  await assert.rejects(saveLeave(token,{...request,request_id:randomUUID()}),/다른 회원/);
  await saveLeave(token,{employee:{...employee,name:'수정',version:1},request_id:randomUUID()});
  assert.equal((await leaveEmployees(token))[0].name,'A');
  await assert.rejects(saveLeave(token,{employee:{...employee,id:randomUUID()},request_id:randomUUID()}),/이미 본인/);
  const unlinked={...employee,id:randomUUID()};
  await (await getDb()).execute({sql:'INSERT INTO leave_employee(id,name,position,hired,special,entries) VALUES (?,?,?,?,?,?)',args:[unlinked.id,'B','사원','2025-01-01',0,'[]']});
  await assert.rejects(saveLeave(other,{employee:unlinked,request_id:randomUUID()}),/본인/);
  await (await getDb()).execute({sql:'INSERT INTO app_admin(singleton,user_id) VALUES(1,?)',args:[b.id]});
  await assert.rejects(saveLeave(other,{employee:{...employee,version:2},request_id:randomUUID()}),/본인/);
  await assert.rejects(saveLeave(token,{employee:{...employee,version:2,entries:[{...employee.entries[0],days:-1}]},request_id:randomUUID()}));
});
