import { after, test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdirSync, mkdtempSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
import { randomUUID } from 'node:crypto';
import { getDb } from '../src/lib/db';
import { loadInventory, mutate, ConflictError } from '../src/lib/inventory';
import { koreaDateTimeInput, koreaDateTimeToUtc } from '../src/lib/korea-time';
mkdirSync('work',{recursive:true});
process.env.JEAGO_TEST_MODE='1';
process.env.JEAGO_TEST_DATABASE_URL=pathToFileURL(join(mkdtempSync(join(resolve('work'),'transaction-edit-')),'test.db')).href;
after(async()=>(await getDb()).close());
const creator={id:'ordinary-creator',display_name:'등록 직원'};
const editor={id:'ordinary-editor',display_name:'수정 직원'};
async function editFields(id: number, overrides: Record<string,unknown> = {}) {
  const data=await loadInventory();
  const row=data.transactions.find(row=>row.id===id)!;
  const target=data.items.find(item=>item.id===Number(overrides.item_id ?? row.item_id))!;
  const source=data.items.find(item=>item.id===row.item_id)!;
  return {action:'transaction.edit',id,original_item_id:row.item_id,item_id:row.item_id,expected_version:row.version,expected_item_version:source.version,expected_target_version:target.version,quantity:row.quantity,transaction_type:row.transaction_type,manager:row.manager,customer_name:row.customer_name || '',date:koreaDateTimeInput(row.date),request_id:randomUUID(),...overrides};
}
test('KST edit values round-trip seconds and milliseconds and reject invalid local dates',()=>{
  assert.equal(koreaDateTimeInput('2026-09-30 15:30:12.345'),'2026-10-01T00:30:12.345');
  assert.equal(koreaDateTimeToUtc('2026-10-01T00:30'),'2026-09-30 15:30:00');
  assert.equal(koreaDateTimeToUtc('2026-10-01T00:30:12.345'),'2026-09-30 15:30:12.345');
  for(const value of ['2026-02-30T12:00','2026-13-01T12:00','2026-09-30T24:00','2026-09-30T12:60','2026-09-30T12:00Z','invalid',''])assert.throws(()=>koreaDateTimeToUtc(value));
});
test('ordinary employees edit all transaction fields atomically while preserving opening balances and audit identity',async()=>{
  const db=await getDb();
  const root=(await loadInventory()).categories[0];
  await mutate({action:'category.add',level:1,parent_id:root.id,name:'편집 테스트 장비'});
  const device=(await loadInventory()).categories.find(c=>c.display_name==='편집 테스트 장비')!;
  await mutate({action:'category.add',level:2,parent_id:device.id,name:'편집 테스트 품목'});
  const category=(await loadInventory()).categories.find(c=>c.display_name==='편집 테스트 품목')!.name;
  for(const name of ['모델 A','모델 B'])await mutate({action:'item.add',name,category},creator);
  const [a,b]=(await loadInventory()).items;
  await db.execute({sql:'UPDATE item SET quantity=5 WHERE id=?',args:[a.id]});
  await db.execute({sql:'UPDATE item SET quantity=2 WHERE id=?',args:[b.id]});
  await mutate({action:'stock.in',id:a.id,quantity:20},creator);
  await mutate({action:'stock.out',id:a.id,quantity:8,customer_name:'원래 업체'},creator);
  await mutate({action:'stock.in',id:b.id,quantity:3},creator);
  const rows=(await loadInventory()).transactions;
  const outgoing=rows.find(row=>row.transaction_type==='출고')!;
  const incoming=rows.find(row=>row.item_id===a.id&&row.transaction_type==='입고')!;
  const fields=await editFields(outgoing.id,{quantity:5,manager:'업무 담당자 정정',customer_name:'정정 업체',date:'2026-10-01T00:30',actor_id:'spoofed'});
  await assert.rejects(mutate(fields),/로그인한 직원/);
  await mutate(fields,editor);
  const snapshot=await loadInventory();
  assert.equal(snapshot.items.find(i=>i.id===a.id)!.quantity,20);
  assert.equal(snapshot.transactions.length,3);
  const saved=snapshot.transactions.find(row=>row.id===outgoing.id)!;
  assert.equal(saved.quantity,5); assert.equal(saved.manager,'업무 담당자 정정');
  assert.equal(saved.date,'2026-09-30 15:30:00'); assert.equal(saved.customer_name,'정정 업체');
  assert.equal(saved.version,1);
  const audit=(await db.execute('SELECT * FROM transaction_edit_audit')).rows;
  assert.equal(audit.length,1); assert.equal(audit[0].actor_id,editor.id); assert.equal(audit[0].actor_name,editor.display_name);
  assert.equal(JSON.parse(String(audit[0].before_data)).quantity,8);
  assert.equal(JSON.parse(String(audit[0].after_data)).quantity,5);
  await mutate(fields,editor);
  assert.deepEqual(await loadInventory(),snapshot);
  assert.equal((await db.execute('SELECT * FROM transaction_edit_audit')).rows.length,1);
  await assert.rejects(mutate({...fields,quantity:4},editor),ConflictError);
  await mutate(await editFields(outgoing.id,{customer_name:'다른 업체'}),creator);
  const metadata=await loadInventory();
  assert.equal(metadata.items.find(i=>i.id===a.id)!.version,snapshot.items.find(i=>i.id===a.id)!.version);
  assert.equal(metadata.transactions.find(row=>row.id===outgoing.id)!.date,saved.date);
  await mutate(await editFields(outgoing.id,{item_id:b.id,quantity:3}),editor);
  let data=await loadInventory();
  assert.equal(data.items.find(i=>i.id===a.id)!.quantity,25);
  assert.equal(data.items.find(i=>i.id===b.id)!.quantity,2);
  await mutate(await editFields(outgoing.id,{transaction_type:'입고',quantity:4}),editor);
  data=await loadInventory();
  assert.equal(data.items.find(i=>i.id===b.id)!.quantity,9);
  assert.equal(data.transactions.find(row=>row.id===outgoing.id)!.customer_name,null);
  const stable=await loadInventory();
  const stableAudit=(await db.execute('SELECT COUNT(*) AS n FROM transaction_edit_audit')).rows[0].n;
  for(const override of [{quantity:0},{quantity:-1},{quantity:'1e2'},{quantity:2147483648},{quantity:2147483647},{manager:''},{transaction_type:'반품'},{date:'2026-02-30T12:00'},{original_item_id:b.id},{expected_version:999},{expected_item_version:undefined},{expected_target_version:undefined},{item_id:999999},{transaction_type:'출고',quantity:99,customer_name:'실패 업체'}]){
    const f=await editFields(incoming.id);
    await assert.rejects(mutate({...f,...override},editor));
    assert.deepEqual(await loadInventory(),stable);
    assert.equal((await db.execute('SELECT COUNT(*) AS n FROM transaction_edit_audit')).rows[0].n,stableAudit);
  }
  // Removing historical inbound units cannot make currently available stock negative.
  await mutate({action:'stock.out',id:a.id,quantity:24,customer_name:'출고 업체'},creator);
  await assert.rejects(mutate(await editFields(incoming.id,{quantity:1}),editor),/수정 후 재고/);
  const staleStock=await editFields(outgoing.id,{quantity:5});
  await mutate({action:'stock.in',id:b.id,quantity:1},creator);
  await assert.rejects(mutate(staleStock,editor),ConflictError);
  const staleTarget=await editFields(incoming.id,{item_id:b.id});
  await mutate({action:'stock.in',id:b.id,quantity:1},creator);
  await assert.rejects(mutate(staleTarget,editor),ConflictError);
  const concurrent=await editFields(outgoing.id,{manager:'동시 수정'});
  const results=await Promise.allSettled([mutate(concurrent,editor),mutate({...concurrent,request_id:randomUUID(),manager:'다른 동시 수정'},creator)]);
  assert.equal(results.filter(r=>r.status==='fulfilled').length,1);
  const archived=await editFields(outgoing.id);
  await mutate({action:'item.delete',id:b.id},creator);
  await assert.rejects(mutate(archived,editor),/모델을 찾을 수 없습니다/);
  await assert.rejects(mutate({...await editFields(incoming.id),item_id:b.id},editor),/모델을 찾을 수 없습니다/);
});
